apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  sa-password: {{ .Values.sqlserver.saPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}